### ISSUE TITLE
Automate the extraction of 'snapshots'

### ISSUE THREAD

**Issue by hannahbrucemacdonald** [choderalab/covid-moonshot-infra#11]
At the moment, there are two semi-duplicate scripts on fah at
`/jdc-analysis-tests/covid-moonshot-infra/covid_moonshot/structures.py`
and
`/jdc-analysis-tests/covid-moonshot-infra/covid_moonshot/structuresHBM.py`

The HBM one differs in three ways:
* as it loops over all runs (1 - v parallelisible)
* tries to find the gen and clone with the lowest reverse work, and then saves it to disk (2 - we will want to replace this)
* tries to avoid opening the `htf.npz` if possible (3 - we will want to move away from this)

**Comment by hannahbrucemacdonald** [comment]
1) the RUNS are completely independent, and we only care about complex phase, so we could just have them run in parallel, or just in an infinite cycle so that it starts with RUN0-> RUNX and then when it's done, start again at RUN0
(no need to run this once `num_work_values` == `300` (or when it's done basically)

**Comment by hannahbrucemacdonald** [comment]
2) this has two parts short and long term
- short term: we can leave it as it is, where this script does some grepping to find the lowest `r_work`, or we could add it as another entry to the `results.json` and look up which snapshot we want from that (because we must be looking at the `r_works` at some point then

- long term: we don't want to just get one snapshot, but do a better job of representing the multitude of data that we are generating. We would want to load in all the snapshots we have, do some clustering on the ligand position, and then either (a) save the ligand/protein complex where the ligand is closest to the centroid of the most populous cluster or (b) a ligand from each cluster to look at

**Comment by hannahbrucemacdonald** [comment]
3) The `htf.npz` is a horrible big pile of very convoluted stuff which takes up more disk space than necessary and isn't very nice to work with. What we want really is basically just `stored_atom_indices`. this information only needs to be extracted once, rather than every time we reevaluate. Ultimately `perses.app.fah_generator` should just save this, so I will open an issue there instead.

**Comment by hannahbrucemacdonald** [comment]
Additional --- we will probably want to add some `sdf` tags to the ligands, but we can add that in.

Also - @jchodera is working on getting the ligand sdf files stitched together (based on the `top-molecules.csv`), into a fragalysis-agreeable format and will probably be aiming to automate having that pushing frequently to fragalysis

**Comment by hannahbrucemacdonald** [comment]
Sorry --- if this is time consuming (and becomes more so with clustering) we care about the structure \propto -binding_fe

if something is +10 kcal/mol we don't care how it binds, so this is something we could use in prioritisation of running the script?

**Comment by mcwitt** [comment]
> Sorry --- if this is time consuming (and becomes more so with clustering) we care about the structure \propto -binding_fe
> 
> if something is +10 kcal/mol we don't care how it binds, so this is something we could use in prioritisation of running the script?

I think that should be straightforward if I'm understanding correctly. I think we could just add a conditional here:
https://github.com/choderalab/covid-moonshot-infra/blob/3d81f6e754fac630608d0a026dfa1557e8306ef6/covid_moonshot/analysis/structures.py#L321
(where we have access to the work values for all clones and gens)

**Comment by hannahbrucemacdonald** [comment]
I think this has been addressed!
