### ISSUE TITLE
Update repo to use MolSSI Cookiecutter

### ISSUE THREAD

**Issue by jchodera** [choderalab/covid-moonshot-infra#13]
We've tried to standardize best practices in repo structure using the [MolSSI CMS Cookiecutter](https://github.com/MolSSI/cookiecutter-cms). At some point, we should restructure the repo to use this.

**Comment by mcwitt** [comment]
I'm planning to implement this here: https://github.com/choderalab/xchem-infrastructure. This repo can be deprecated when the transition is complete.

**Comment by jchodera** [comment]
Awesome!
