### ISSUE TITLE
Leave unreasonable relative free energies from analysis

### ISSUE THREAD

**Issue by hannahbrucemacdonald** [choderalab/covid-moonshot-infra#29]
There is a result with a relative free energy of ~700 kT, which is presumably something going wrong. This messes up the plotting of results:
![image](https://user-images.githubusercontent.com/43652597/91028256-1f1d8d00-e5f5-11ea-8157-0bbff541af5d.png)

I think we can skip results that have unreasonable relative binding free energies (larger than +/- 30kT)? And flag them either for rerunning, or human intervention (possibly just throwing out one messed up GEN?)

**Comment by mcwitt** [comment]
This should be (partially) addressed in https://github.com/choderalab/covid-moonshot-infra/pull/34 (specifically https://github.com/choderalab/covid-moonshot-infra/pull/34/commits/e0cdbdfa21c603df7d1b3df2d1f4a73cceaf0bb7).

So far this is only omitting relative FEs outside the valid range from the distribution plots, but they are still included in the JSON.

**Comment by mcwitt** [comment]
Fixed in #34
