### ISSUE TITLE
Colour on relative free energy plots aren't matching

### ISSUE THREAD

**Issue by hannahbrucemacdonald** [choderalab/covid-moonshot-infra#48]
Super minor -- but the rugplot and kdeplot are different colours for relative free energy plot. Looking at the code, I can't work out why they're not

![image](https://user-images.githubusercontent.com/43652597/91706447-4f75a600-eb76-11ea-929a-9e35cf3de5e9.png)

**Comment by mcwitt** [comment]
My fault, I messed this up in in #34. Fixed in d963f9c.
