### ISSUE TITLE
Need table to help identify poor convergence 

### ISSUE THREAD

**Issue by WG150** [choderalab/covid-moonshot-infra#53]
Looking through the convergence plots automatically generated it is hard to assess the large number of plots for bad convergence. This is particularly important for the complex phase. It would be good to get a table as a PDF that identifies JOBIDs with poor complex convergence to speed up identification of problematic RUNs.

**Comment by hannahbrucemacdonald** [comment]
I think it is interesting if

a) there is significant variance between the calculated binding affinity per GEN
or
b) if there is a _trend_ in the free energies between GENS, i.e. does the calculated affinity of the new ligand increase/decrease with additional compute time, and if so, how does this correlate with relaxation in the protein-ligand complexes.


Conversely, these convergence plots might be helpful in identifying if we need 3, 5, 10... GENS per RUN to get reliable predicted affinities, however this will probably require more experimental results to assess

**Comment by mcwitt** [comment]
@WG150 can we close this with #54?

**Comment by WG150** [comment]
@mcwitt yes!

**Comment by mcwitt** [comment]
Implemented in #54
