### ISSUE TITLE
Date+time in all output

### ISSUE THREAD

**Issue by hannahbrucemacdonald** [choderalab/covid-moonshot-infra#56]
Especially with the files being updated live-online and that it's regenerated so frequently, it might be worth putting a timestamp on/in all files and figures.

It hasn't happened yet, but I can imagine there being a case where one person thinks the top ligand is X, another one thinks its Y and having a receipt on stuff would help figure out what's more new

**Comment by mcwitt** [comment]
Thanks, this seems very useful/important! I'll add a "high-priority" tag.
